### ISSUE TITLE
[Feature Request] Consistent Clean Race bonus 

### ISSUE THREAD

**Issue by RonSpawnson** [aimerror/granturismo#2]
I notice sometimes I get a clean race yet many times I don't. It often smashes hard into a car in front.

Not sure how easy of an adjustment this would be but the idea would be to improve payout by increasing likelihood of clean race bonus. Thinking about something like decelerating if approaching another car, until that car is out of our path. Which will probably be the next corner. Then it can whiz past again.

**Comment by jilderthoekstra** [comment]
Do you have this problem with the tomahawk S vgt? I only watched a couple of runs with the script running where it did bump into other cars but it still gave me a clean race bonus.

**Comment by RonSpawnson** [comment]
Yes I'm using Tomahawk S VGT. Seems sometimes it gives clean race bonus, others it doesn't. Somewhat random

I do notice around 600k per hour as you do, which is still pretty great, clean bonus or not

**Comment by RonSpawnson** [comment]
I'm going to close this issue. The latest code from today hugs the wall much more tightly than before and I'm now noticing consistent clean race bonuses (even though cars are hit at beginning)
