### ISSUE TITLE
Nothing happens after script execution

### ISSUE THREAD

**Issue by mkandan** [aimerror/granturismo#3]
Hey, first off thanks for putting this together, glad to see a solution coming out of PD's hot mess.

I'm on Windows 10.0.18363.1440. Did a fresh install of python 3.1, pip, all the dependencies you listed, Chiaki (got my PS5 manually connected, and confirmed it works with the wake up packet test), and downloaded the Auto Hotkey app).

After executing "python gran_turismo.py" from the granturismo-main folder, nothing happens..I just get a new line in Powershell. I also went into File explorer to double-click execute, and a command prompt window titled "Select C:\\WINDOWS\py.exe" pops up and closes immediately same happens when i double click any of the other python executables in the repo's base level.

**Comment by jilderthoekstra** [comment]
Hmm. Did you install python 3.1 or 3.10?
Open a PowerShell and type: python --version
Just to make sure python is working. It should display the python version.
