### ISSUE TITLE
Stuck in menus. 

### ISSUE THREAD

**Issue by nicholaicascio** [aimerror/granturismo#5]
I seem to be getting stuck in the menus about once every hour or two. I'm not sure but my guess would be that an input is delivered during a momentary lapse in latency and it never makes it over the internet to my PS5. The commands are delivered as a simple series of inputs and I don't see what else could be messing this up other than an input failing to make it from Chiaki to the PS5. 

Has anyone troubleshooted this sort of thing? I tried adding some delays at places in the code to give the stream a half second pause between inputs in this sequence, but that still hasn't solved the issue 100% of the time. 

The most common place it gets stuck is before pressing: Right, and then Next Race.

Any help is appreciated.

**Comment by azbelj** [comment]
Are you doing anything else on your pc while it runs? it can interrupt the script

**Comment by nicholaicascio** [comment]
@azbelj I noticed that and no, I just let it run on it's own.

**Comment by jilderthoekstra** [comment]
I'll look into it. I'll see if I can change it so it doesn't depends on a sleep value but will scan for the logo or something like it does for returning to the world screen.

I'm currently also changing the whole capture and input method so that the stream window doesn't need focus. That way you could still use your PC.

**Comment by nicholaicascio** [comment]
Pulling new changes for testing. Thanks for that, I haven't had enough time to tinker so you're really carrying us man! I'll close this when I get a chance to test it in a bit.
